MODEL:
  BERT_CKPT: "macbert4csc-base-chinese"
  DEVICE: "cuda"
  NAME: "macbert4csc"
  GPU_IDS: [0,1,2,3]
  # [loss_coefficient]
  HYPER_PARAMS: [0.3]
  #WEIGHTS: "output/macbert4csc/epoch=6-val_loss=0.07.ckpt"
  WEIGHTS: ""

DATASETS:
  TRAIN: "output/train.json"
  VALID: "output/dev.json"
  TEST: "output/test.json"

SOLVER:
  BASE_LR: 5e-5
  WEIGHT_DECAY: 0.01
  BATCH_SIZE: 64
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 4

OUTPUT_DIR: "output/macbert4csc"
MODE: ["train", "test"]
